// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/converter.dart';
import 'api/file_ops.dart';
import 'api/format.dart';
import 'api/models.dart';
import 'api/playback.dart';
import 'api/playlist.dart';
import 'api/scanner.dart';
import 'api/search.dart';
import 'api/trimmer.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Playlist dco_decode_box_autoadd_playlist(dynamic raw);

  @protected
  DeleteResult dco_decode_delete_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LyricsEntry> dco_decode_list_lyrics_entry(dynamic raw);

  @protected
  List<PlayCountEntry> dco_decode_list_play_count_entry(dynamic raw);

  @protected
  List<Playlist> dco_decode_list_playlist(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SongMetadata> dco_decode_list_song_metadata(dynamic raw);

  @protected
  LyricsEntry dco_decode_lyrics_entry(dynamic raw);

  @protected
  NextSongResult dco_decode_next_song_result(dynamic raw);

  @protected
  PlayCountEntry dco_decode_play_count_entry(dynamic raw);

  @protected
  Playlist dco_decode_playlist(dynamic raw);

  @protected
  RenameResult dco_decode_rename_result(dynamic raw);

  @protected
  SongMetadata dco_decode_song_metadata(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Playlist sse_decode_box_autoadd_playlist(SseDeserializer deserializer);

  @protected
  DeleteResult sse_decode_delete_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LyricsEntry> sse_decode_list_lyrics_entry(SseDeserializer deserializer);

  @protected
  List<PlayCountEntry> sse_decode_list_play_count_entry(
      SseDeserializer deserializer);

  @protected
  List<Playlist> sse_decode_list_playlist(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SongMetadata> sse_decode_list_song_metadata(
      SseDeserializer deserializer);

  @protected
  LyricsEntry sse_decode_lyrics_entry(SseDeserializer deserializer);

  @protected
  NextSongResult sse_decode_next_song_result(SseDeserializer deserializer);

  @protected
  PlayCountEntry sse_decode_play_count_entry(SseDeserializer deserializer);

  @protected
  Playlist sse_decode_playlist(SseDeserializer deserializer);

  @protected
  RenameResult sse_decode_rename_result(SseDeserializer deserializer);

  @protected
  SongMetadata sse_decode_song_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_playlist(Playlist self, SseSerializer serializer);

  @protected
  void sse_encode_delete_result(DeleteResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyrics_entry(
      List<LyricsEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_play_count_entry(
      List<PlayCountEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_playlist(List<Playlist> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(
      Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_song_metadata(
      List<SongMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_entry(LyricsEntry self, SseSerializer serializer);

  @protected
  void sse_encode_next_song_result(
      NextSongResult self, SseSerializer serializer);

  @protected
  void sse_encode_play_count_entry(
      PlayCountEntry self, SseSerializer serializer);

  @protected
  void sse_encode_playlist(Playlist self, SseSerializer serializer);

  @protected
  void sse_encode_rename_result(RenameResult self, SseSerializer serializer);

  @protected
  void sse_encode_song_metadata(SongMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
