// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_to_mp3_transcode`, `extract_aac_lossless`, `make_adts_header`

/// Native FFI conversion engine from video to audio (MP3/M4A).
///
/// Automatically attempts fast lossless demuxing for M4A outputs,
/// and falls back to full PCM decoding and MP3 encoding for all formats.
Future<String> convertMediaFile(
        {required String inputPath,
        required String outputPath,
        required String targetFormat}) =>
    RustLib.instance.api.crateApiConverterConvertMediaFile(
        inputPath: inputPath,
        outputPath: outputPath,
        targetFormat: targetFormat);
