// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build a safe destination file path for renaming.
RenameResult buildRenamePath(
        {required String originalPath, required String newName}) =>
    RustLib.instance.api.crateApiFileOpsBuildRenamePath(
        originalPath: originalPath, newName: newName);

/// Execute a physical file rename (copy + delete source).
Future<RenameResult> renameFile(
        {required String originalPath, required String newPath}) =>
    RustLib.instance.api.crateApiFileOpsRenameFile(
        originalPath: originalPath, newPath: newPath);

/// Execute a physical file deletion.
Future<DeleteResult> deleteFile({required String path}) =>
    RustLib.instance.api.crateApiFileOpsDeleteFile(path: path);

/// Update a song path in all playlists when it is renamed.
List<Playlist> updatePlaylistsAfterRename(
        {required List<Playlist> playlists,
        required String oldPath,
        required String newPath}) =>
    RustLib.instance.api.crateApiFileOpsUpdatePlaylistsAfterRename(
        playlists: playlists, oldPath: oldPath, newPath: newPath);
