// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Utility formatters: duration, file size, URL detection, filename sanitization.
/// Format seconds into "M:SS" or "H:MM:SS".
String formatDuration({required double seconds}) =>
    RustLib.instance.api.crateApiFormatFormatDuration(seconds: seconds);

/// Format bytes into a human-readable string (e.g. "3.2 MB").
String formatFileSize({required PlatformInt64 bytes}) =>
    RustLib.instance.api.crateApiFormatFormatFileSize(bytes: bytes);

/// Check whether the input string is a YouTube URL.
bool isYoutubeUrl({required String input}) =>
    RustLib.instance.api.crateApiFormatIsYoutubeUrl(input: input);

/// Remove invalid filesystem characters from a filename.
String sanitizeFilename({required String name}) =>
    RustLib.instance.api.crateApiFormatSanitizeFilename(name: name);

/// Sanitize a download filename (same rules as sanitize_filename).
String sanitizeDownloadFilename({required String name}) =>
    RustLib.instance.api.crateApiFormatSanitizeDownloadFilename(name: name);
