// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Result of a file delete operation.
class DeleteResult {
  final bool success;
  final String error;

  const DeleteResult({
    required this.success,
    required this.error,
  });

  @override
  int get hashCode => success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error;
}

/// A single lyrics entry (song path → lyrics text).
class LyricsEntry {
  final String path;
  final String lyrics;

  const LyricsEntry({
    required this.path,
    required this.lyrics,
  });

  @override
  int get hashCode => path.hashCode ^ lyrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          lyrics == other.lyrics;
}

/// Result of a next/previous song index calculation.
class NextSongResult {
  final int index;
  final bool found;

  const NextSongResult({
    required this.index,
    required this.found,
  });

  @override
  int get hashCode => index.hashCode ^ found.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NextSongResult &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          found == other.found;
}

/// A single play-count entry (song path → count).
class PlayCountEntry {
  final String path;
  final PlatformInt64 count;

  const PlayCountEntry({
    required this.path,
    required this.count,
  });

  @override
  int get hashCode => path.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayCountEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          count == other.count;
}

/// A user-created or system playlist.
class Playlist {
  final String name;
  final List<String> songs;
  final bool isSystem;

  const Playlist({
    required this.name,
    required this.songs,
    required this.isSystem,
  });

  @override
  int get hashCode => name.hashCode ^ songs.hashCode ^ isSystem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          songs == other.songs &&
          isSystem == other.isSystem;
}

/// Result of a file rename operation.
class RenameResult {
  final bool success;
  final String newPath;
  final String error;

  const RenameResult({
    required this.success,
    required this.newPath,
    required this.error,
  });

  @override
  int get hashCode => success.hashCode ^ newPath.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          newPath == other.newPath &&
          error == other.error;
}

/// Shared data models for the Jezsic music app.
///
/// All structs here are passed across the Flutter ↔ Rust FFI boundary.
/// Audio file metadata extracted during filesystem scanning.
class SongMetadata {
  final String title;
  final String artist;
  final String album;
  final double durationSeconds;
  final String path;
  final PlatformInt64 modifiedDate;
  final String coverPath;

  const SongMetadata({
    required this.title,
    required this.artist,
    required this.album,
    required this.durationSeconds,
    required this.path,
    required this.modifiedDate,
    required this.coverPath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSeconds.hashCode ^
      path.hashCode ^
      modifiedDate.hashCode ^
      coverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSeconds == other.durationSeconds &&
          path == other.path &&
          modifiedDate == other.modifiedDate &&
          coverPath == other.coverPath;
}
