// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayCountJson`, `PlaylistJson`

/// Serialize user playlists to JSON (excludes system playlists).
String serializePlaylists({required List<Playlist> playlists}) =>
    RustLib.instance.api
        .crateApiPlaylistSerializePlaylists(playlists: playlists);

/// Deserialize user playlists from JSON.
List<Playlist> deserializePlaylists({required String json}) =>
    RustLib.instance.api.crateApiPlaylistDeserializePlaylists(json: json);

/// Serialize play counts to JSON string.
String serializePlayCounts({required List<PlayCountEntry> entries}) =>
    RustLib.instance.api.crateApiPlaylistSerializePlayCounts(entries: entries);

/// Deserialize play counts from JSON string.
List<PlayCountEntry> deserializePlayCounts({required String json}) =>
    RustLib.instance.api.crateApiPlaylistDeserializePlayCounts(json: json);

/// Serialize lyrics to JSON string.
String serializeLyrics({required List<LyricsEntry> entries}) =>
    RustLib.instance.api.crateApiPlaylistSerializeLyrics(entries: entries);

/// Deserialize lyrics from JSON string.
List<LyricsEntry> deserializeLyrics({required String json}) =>
    RustLib.instance.api.crateApiPlaylistDeserializeLyrics(json: json);

/// Compute the top N most-played song paths, sorted by count descending.
List<String> computeFavorites(
        {required List<PlayCountEntry> entries, required int limit}) =>
    RustLib.instance.api
        .crateApiPlaylistComputeFavorites(entries: entries, limit: limit);

/// Add a song to a playlist (no duplicates). Returns the updated playlist.
Playlist addSongToPlaylist(
        {required Playlist playlist, required String songPath}) =>
    RustLib.instance.api.crateApiPlaylistAddSongToPlaylist(
        playlist: playlist, songPath: songPath);

/// Remove a song from a playlist. Returns the updated playlist.
Playlist removeSongFromPlaylist(
        {required Playlist playlist, required String songPath}) =>
    RustLib.instance.api.crateApiPlaylistRemoveSongFromPlaylist(
        playlist: playlist, songPath: songPath);
