// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Calculate the next song index.
///
/// loop_mode: "off", "all", or "one".
NextSongResult nextSongIndex(
        {required int currentIndex,
        required int playlistLength,
        required bool isShuffle,
        required String loopMode,
        required PlatformInt64 timestampSeed}) =>
    RustLib.instance.api.crateApiPlaybackNextSongIndex(
        currentIndex: currentIndex,
        playlistLength: playlistLength,
        isShuffle: isShuffle,
        loopMode: loopMode,
        timestampSeed: timestampSeed);

/// Calculate the previous song index.
///
/// If position_seconds > 3, it should restart the current song instead of moving back.
NextSongResult prevSongIndex(
        {required int currentIndex,
        required int playlistLength,
        required bool isShuffle,
        required int positionSeconds,
        required PlatformInt64 timestampSeed}) =>
    RustLib.instance.api.crateApiPlaybackPrevSongIndex(
        currentIndex: currentIndex,
        playlistLength: playlistLength,
        isShuffle: isShuffle,
        positionSeconds: positionSeconds,
        timestampSeed: timestampSeed);
