// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_metadata`

/// Build a deduplicated list of directories to scan.
///
/// Combines default Android paths with any additional external root.
Future<List<String>> buildScanPaths(
        {required String basePath, required String externalRoot}) =>
    RustLib.instance.api.crateApiScannerBuildScanPaths(
        basePath: basePath, externalRoot: externalRoot);

/// Recursively scan directories for audio files and extract metadata.
///
/// Runs on a native OS thread — never blocks the Dart UI.
Future<List<SongMetadata>> scanMusicFiles(
        {required List<String> directories, required String cacheDir}) =>
    RustLib.instance.api.crateApiScannerScanMusicFiles(
        directories: directories, cacheDir: cacheDir);
