// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Search and sort algorithms for song lists.
/// Case-insensitive substring search on title and artist.
///
/// Returns indices of matching songs in the original list.
Future<Int32List> searchSongs(
        {required List<String> titles,
        required List<String> artists,
        required String query}) =>
    RustLib.instance.api.crateApiSearchSearchSongs(
        titles: titles, artists: artists, query: query);

/// Sort songs and return sorted indices.
///
/// `sort_by`: `"title"`, `"artist"`, or `"date"` (default: newest first).
Future<Int32List> sortSongs(
        {required List<String> titles,
        required List<String> artists,
        required Int64List modifiedDates,
        required String sortBy}) =>
    RustLib.instance.api.crateApiSearchSortSongs(
        titles: titles,
        artists: artists,
        modifiedDates: modifiedDates,
        sortBy: sortBy);
