// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Recursively scan directories for audio files and extract metadata.
/// Runs on a native OS thread — never blocks the Dart UI.
Future<List<SongMetadata>> scanMusicFiles(
        {required List<String> directories, required String cacheDir}) =>
    RustLib.instance.api.crateApiSimpleScanMusicFiles(
        directories: directories, cacheDir: cacheDir);

/// Search songs by a case-insensitive substring match on title and artist.
/// Returns indices of matching songs in the original list.
Future<Int32List> searchSongs(
        {required List<String> titles,
        required List<String> artists,
        required String query}) =>
    RustLib.instance.api.crateApiSimpleSearchSongs(
        titles: titles, artists: artists, query: query);

/// Sort songs and return sorted indices.
/// `sort_by` can be "title", "artist", or "date".
Future<Int32List> sortSongs(
        {required List<String> titles,
        required List<String> artists,
        required Int64List modifiedDates,
        required String sortBy}) =>
    RustLib.instance.api.crateApiSimpleSortSongs(
        titles: titles,
        artists: artists,
        modifiedDates: modifiedDates,
        sortBy: sortBy);

/// Metadata extracted from an audio file.
class SongMetadata {
  final String title;
  final String artist;
  final String album;
  final double durationSeconds;
  final String path;
  final PlatformInt64 modifiedDate;
  final String coverPath;

  const SongMetadata({
    required this.title,
    required this.artist,
    required this.album,
    required this.durationSeconds,
    required this.path,
    required this.modifiedDate,
    required this.coverPath,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSeconds.hashCode ^
      path.hashCode ^
      modifiedDate.hashCode ^
      coverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSeconds == other.durationSeconds &&
          path == other.path &&
          modifiedDate == other.modifiedDate &&
          coverPath == other.coverPath;
}
