// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Trim an MP3 file losslessly from start_secs to end_secs.
///
/// Automatically copies original ID3 tags to preserve album art and metadata.
Future<String> trimMp3(
        {required String inputPath,
        required String outputPath,
        required double startSecs,
        required double endSecs}) =>
    RustLib.instance.api.crateApiTrimmerTrimMp3(
        inputPath: inputPath,
        outputPath: outputPath,
        startSecs: startSecs,
        endSecs: endSecs);

/// Trim a WAV file from start_secs to end_secs by slicing PCM bytes and updating header size.
Future<String> trimWav(
        {required String inputPath,
        required String outputPath,
        required double startSecs,
        required double endSecs}) =>
    RustLib.instance.api.crateApiTrimmerTrimWav(
        inputPath: inputPath,
        outputPath: outputPath,
        startSecs: startSecs,
        endSecs: endSecs);
